package com.jubaer.koreanflashcards

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "vocab_words_cache")
data class VocabWordEntity(
    @PrimaryKey val korean_word: String,
    val bangla_meaning: String,
    val chapter_number: Int
)

@Entity(tableName = "flashcard_progress_cache")
data class ProgressEntity(
    @PrimaryKey val korean_word: String,
    val box_level: Int,
    val next_review_date: String,
    val times_reviewed: Int,
    val times_correct: Int
)

/**
 * Dialogue Reader থেকে সেভ করা একটা পুরো chapter — offline এ পরে পড়ার জন্য।
 * প্রতিটা chapter এ ৩টা অংশ থাকে: কথপোকথন ১, কথপোকথন ২, তথ্য/সংস্কৃতি।
 * প্রতিটা অংশের turns (বাক্য/বাবল) ও glossary (শব্দ → অর্থ) আলাদা আলাদা JSON
 * text আকারে সেভ করা হয় (org.json দিয়ে বানানো, দেখো DialogueModels.kt এর
 * ChapterJson object), যাতে নতুন কোনো library লাগে না এবং local DB তে থাকায়
 * internet ছাড়াই পরে পুরোটা পড়া যায়।
 */
@Entity(tableName = "dialogue_chapters")
data class DialogueChapterEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val chapterName: String,
    val dialogue1Turns: String,
    val dialogue1Glossary: String,
    val dialogue2Turns: String,
    val dialogue2Glossary: String,
    val cultureTurns: String,
    val cultureGlossary: String,
    val createdAt: Long
)


/** Missing dialogue-word meanings generated by Gemini are cached locally here. */
@Entity(tableName = "dialogue_word_meanings")
data class DialogueWordMeaningEntity(
    @PrimaryKey val koreanWord: String,
    val banglaMeaning: String,
    val source: String,
    val updatedAt: Long
)
